version: '3.9'

services:
  localstack:
    image: localstack/localstack:2.0
    environment:
      - SERVICES=sqs
      - AWS_DEFAULT_REGION=us-east-1
      - HOSTNAME_EXTERNAL=localhost
    volumes:
      - ./local/localstack:/etc/localstack/init/ready.d
    ports:
      - "4566:4566"
  mongodb:
    image: mongo:4.2
    restart: always
    environment:
      MONGO_INITDB_DATABASE: workflows
    ports:
      - "27017:27017"
